console.log("-------Variables for Each Data Types-------\n");
console.log("-------------String Data Type--------------");
var myName="Ajay Sonawane";
console.log("My Name is:", myName);
console.log("Data Type is:", typeof myName);
console.log("-------------Number Data Type--------------");
var age=30;
console.log("Age is:", age);
console.log("Data Type is:", typeof age);
console.log("-------------Boolean Data Type-------------");
var isMarried=true;
console.log("is Married:", isMarried);
console.log("Data Type is", typeof isMarried);
console.log("=====================================================\n");
console.log("----Diffrence Between Null Vs Undefined-----\n");
console.log("------Undefined Variables and Data Type-----");
// var myFullName="Ajay Ramchandra Sonawane";
// console.log("My Full Name:", myFullName);
var myFullName;
console.log("My Full Name is:", myFullName);
console.log("Data Type is:", typeof myFullName);
console.log("* when we will declare a variable but do not assign a value to it, the variable becomes undefined.\n");
console.log("--------Null Variables and Data Type--------");
var age=null;
console.log("My Age is:", age);
console.log("Data Type is:", typeof age);
console.log("* When we will assign null as a value to any variable, it means that it is empty or blank.");
console.log("Also, null is an object in JavaScript.");

