console.log("-----------Before Initialize Variable------------");
var myFullName;
console.log(myFullName);
console.log("----------After Initialize Variable--------------");
myFullName="Ajay Sonawane";
console.log(myFullName);
console.log("-----------------Update Full Name----------------");
myFullName="Ajay Ramchandra Sonawane";
console.log(myFullName);
console.log("----------Declare and Initialize variable--------");
var myLove;
myLove="My Love Only JS";
console.log("My Love:", myLove);
console.log("      ----------Personal Details------------      ");
console.log("----------------------------------------------------------------------------");
var firstName="Ajay";
var lastName="Sonawane";
var age=30;
var address="Pune";
var pinCode=110018;
var gender="Male";
var isMarried="Married";
console.log("| First Name  | Last Name| Age | Address| Pin_Code   | Gender | Is Married |");
console.log("----------------------------------------------------------------------------");
console.log("|   ", firstName,"    |", lastName,"|",  age," |",  address,"  |",    pinCode,"    |",   gender,"  |",   isMarried, "   |");
console.log("----------------------------------------------------------------------------");
