console.log("-------------Swap Two Variables Values--------------\n");
console.log("----------------Before Swap Values------------------");
var sweety="Sweety";
var cutie="Cutie";
console.log(sweety, cutie);
console.log("----------------After Swap Values-------------------");
var temp=sweety;
sweety=cutie;
cutie=temp;
console.log(sweety, cutie);
console.log("============================================================\n");
console.log("--------------Swap Three Variables Values-------------\n");
console.log("----------------Befor Swap Three Values---------------");
var num1=100;
var num2=200;
var num3=300;
console.log(num1, num2, num3);
console.log("----------------After Swap Three Values---------------");
var num4=num1;
num1=num2;
num2=num3;
num3=num4;
console.log(num1, num2, num3);
