console.log('-------------Before Initialization Data Type----------');
var bankName;
console.log('Bank Name:', bankName);
console.log('Data Type:', typeof bankName);
console.log('-------------After Initialization Data Type-----------');
var bankName='SBI Bank';
console.log("Bank Name:", bankName);
console.log('Data Type:', typeof bankName);
console.log('------------------------------------------------------');
var mark=90;
console.log('Mark is:', mark);
console.log('Data Type:', typeof mark);
console.log('-------------Before Initialization Variable-----------');
var isWorking;
console.log('Variable is:', isWorking);
console.log('-------------After Initialization Variable------------');
isWorking=true;
console.log('Result is:', isWorking);
console.log('Data Type:', typeof isWorking);
console.log("-----------Initialize and Declare variable------------");
var totalCount="Hundered and Seven";
console.log('Total Count is:', totalCount);
console.log('Data Type is:', typeof totalCount);
console.log('-----------Update Variable with New Value-------------');
totalCount=107;
console.log('Total Count is:', totalCount);
console.log('Data Type is:', typeof totalCount);
